# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: aurora-custom-rtx
description: Aurora Linux DX com NVIDIA RTX, Snap, Mullvad e TLS 1.0.
# Já inicia com a base de desenvolvedor para evitar o erro de rebase 403
base-image: ghcr.io/ublue-os/aurora-dx-nvidia 
image-version: stable

modules:
  - type: script
    scripts:
      - add-repos.sh

  - type: rpm-ostree
    install:
      - mullvad-vpn
      - snapd
      - crypto-policies-scripts
      - fuse
      - libayatana-appindicator-gtk3 # Versão atualizada do libappindicator

  - type: kargs
    kargs:
      - ssl.allow_unsafe_legacy_renegotiation=1

  - type: default-flatpaks
    configurations:
      - system: true
        install:
          - io.dbeaver.DBeaverCommunity
          - com.slack.Slack

  - type: script
    scripts:
      - post-install.sh