# recipe.yml
name: aurora-custom-rtx
description: Aurora Linux DX com NVIDIA RTX, Snap, Mullvad e TLS 1.0.
# Mudamos a base para dx para já vir com ferramentas de dev e grupos
base-image: ghcr.io/ublue-os/aurora-dx-nvidia 
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - mullvad-vpn
      - snapd
      - crypto-policies-scripts
      - fuse
      # Adicionamos bibliotecas necessárias para o RiseupVPN
      - libappindicator-gtk3 

  - type: kargs
    kargs:
      - ssl.allow_unsafe_legacy_renegotiation=1

  - type: default-flatpaks
    configurations:
      - system: true
        install:
          - io.dbeaver.DBeaverCommunity
          - com.slack.Slack

  - type: script
    scripts:
      - post-install.sh