# recipe.yml
name: aurora-custom-rtx
description: Aurora Linux com NVIDIA RTX, Snap, Mullvad, Slack e TLS 1.0 Legacy.
base-image: ghcr.io/ublue-os/aurora-nvidia
image-version: stable

modules:
  - type: script
    scripts:
      - add-repos.sh # Roda primeiro para configurar o repo

  - type: rpm-ostree
    install:
      - mullvad-vpn
      - snapd
      - crypto-policies-scripts
      - fuse

  - type: kargs # Forma correta de adicionar argumentos de kernel
    kargs:
      - ssl.allow_unsafe_legacy_renegotiation=1

  - type: default-flatpaks
    configurations:
      - system: true
        install:
          - io.dbeaver.DBeaverCommunity
          - com.slack.Slack

  - type: script
    scripts:
      - post-install.sh