name: aurora-custom-rtx
description: Aurora Linux com NVIDIA RTX, Snap, Mullvad, Slack e TLS 1.0 Legacy.
base-image: ghcr.io/ublue-os/aurora-nvidia
image-version: stable
modules:
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/x86_64/mullvad.repo
    install:
      - mullvad-vpn
      - snapd
      - crypto-policies-scripts
      - fuse
  - type: flatpak
    install:
      - io.dbeaver.DBeaverCommunity
      - com.slack.Slack
  - type: script
    scripts:
      - post-install.sh
