name: bluebuild
on:
  schedule:
    - cron: "00 17 * * *"
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    uses: blue-build/github-action/.github/workflows/build.yml@v1
    with:
      recipe: recipe.yml
      pr_event_number: ${{ github.event.number }}
      # Removemos a tentativa manual de passar secrets aqui para evitar erros
    secrets: inherit