name: Build Aurora Custom RTX ISO
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Build semanal para manter drivers NVIDIA atualizados
  workflow_dispatch: # Permite rodar manualmente

jobs:
  bluebuild:
    name: Build Custom Image and ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          # Ativa a geração da ISO após o build da imagem
          maximize_build_space: true
          generate_iso: true
          upload_privileged: true

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aurora-RTX-Custom-ISO
          path: |
            ./*.iso
            ./*.iso-sha256sum
          if-no-files-found: error
          retention-days: 7